# Create this file as .streamlit/config.toml in your project root
# Claude AI Inspired Theme 🤖

[theme]
base = "light"
primaryColor = "#D97706"
backgroundColor = "#FEFBF3"
secondaryBackgroundColor = "#F5F1E8"
textColor = "#1F2937"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
port = 8501
baseUrlPath = ""
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
showErrorDetails = true   # ✅ This one is fine to keep

[runner]
magicEnabled = true
postScriptGC = true
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
